;; Do not edit.  Generated by lein-git-version plugin.
(ns ropen-sci-cloud.version)
(def version "0.1.1")
(def info {
  :date "Sun Sep 28 23:19:28 2014 +0200"
  :revision "8f691bf5ea905893383207d25d06f0268d467cdc"
  :author "Carsten Behring <carsten.behring@gmail.com>"
  :version "0.1.1"
})
